apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameoflife-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mudaykumar/game-of-life-jenkins:v1
        imagePullPolicy: Always
        envFrom: 
          - configMapRef:
              name: demo-configmap

